version: '3'

networks:
  proxy:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    container_name: nginx-container
    image: nginx:latest
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - proxy
    depends_on:
      - app
    tty: true
  
  app:
    build:
      context: node
    container_name: app-container
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install && npm start"
    networks:
      - proxy
      - backend
    volumes:
      - ./node:/usr/src/app
    tty: true
    expose: [3000]
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-db-container
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
